channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.10.9
  - tesseract=4.1.1
  - pip=23.0.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==27.7.0 # https://rpaframework.org/releasenotes.html
      - pycryptodome==3.22.0
      - oracledb==3.0.0
      - XlsxWriter==3.2.2
      - rpaframework-recognition==5.2.3
      - pandas==2.1.4
      - pyodbc==4.0.39
      - abydos==0.5.0
      - python-Levenshtein==0.21.1
      - nepali-datetime==1.0.8.3
      - rapidfuzz==3.6.1
      - openpyxl==3.1.2
      - psycopg2-binary==2.9.10
      - SQLAlchemy==2.0.30
      - openpyxl==3.1.5
      - oracledb==1.4.2
      - tenacity==9.0.0
      - pydantic==2.10.2

